services:
  db:
    image: postgres:16-alpine
    container_name: ptms-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pickleball_tms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 140903
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pickleball_tms"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ptms-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/pickleball_tms
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 140903
      JWT_SECRET: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    ports:
      - "3000:8080"

volumes:
  pgdata:
