databases:
  - name: ptms-db
    plan: free
    databaseName: pickleball_tms

services:
  - type: web
    name: ptms-app
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ptms-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
