spring.application.name=backend
server.port=${PORT:8080}
spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:5432/pickleball_tms}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:140903}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# Speed up startup on Render free tier (slow CPU)
spring.main.lazy-initialization=true

logging.level.org.springframework.security=WARN

# App properties
app.jwt-secret=${JWT_SECRET:daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb}
app.jwt-expiration-milliseconds=604800000